---
engines:
  cppcheck:
    enabled: true
    config:
      check: all
      language: c++
      stds:
        - c++11
      platform: unix64
      defines:
      - "DEBUG=1"
      - "__cplusplus"
      undefines:
      - "DEBUG"
      includes:
      - include/
      max_configs: 42
      inconclusive: false
  csslint:
    enabled: false
  duplication:
    enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: false
  radon:
    enabled: false
exclude_paths: []
