---
engines:
  cppcheck:
    enabled: true
    config:
      check: all
      language: c++
      stds:
        - c++11
      platform: unix64
  csslint:
    enabled: false
  duplication:
    enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: false
  radon:
    enabled: false
exclude_paths: []
