language: cpp

compiler:  
    - gcc
    
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
    - os: linux
      dist: jessie
      sudo: required
    - os: linux
      dist: sid
      sudo: required

before_install:
  - sudo apt-get update
  
install:
  - sudo apt-get -y install build-essential libsdl1.2-dev libsdl-image1.2-dev g++-4.8 gcc-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:  
    - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release 

script: 
    - cmake --build build 

os:
    - linux
    
notifications:
    on_success: change
    on_failure: change
