version: '{branch}-{build}'
image: Visual Studio 2013
clone_folder: c:\projects\roland-12
environment:
  matrix:
  - GENERATOR: '"Visual Studio 12 2013 Win64"'
  - GENERATOR: '"Visual Studio 12 2013"'
cache: c:\projects\roland-12\build
build_script:
- cmd: >-
    cd C:\projects\roland-12

    cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -G %GENERATOR%

    cmake --build build --config Release --target roland
artifacts:
- path: build\bin
  name: bin